//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OrderPlacement.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Package
    {
        public int id { get; set; }
        public string Package1 { get; set; }
        public Nullable<int> QTY { get; set; }
        public Nullable<decimal> SubTotal { get; set; }
        public Nullable<decimal> Total { get; set; }
    }
}
